### ISSUE TITLE
Tries to despawn objects as non-host

### ISSUE THREAD

**Issue by sockbats** [LethalCompanyModding/Enhancer#7]
I was getting this error when we wiped as two players. This issue persisted whenever we both died until I turned off SAVE_COINFLIP, so my only guess was that it was what caused it.
![Lethal_Company_1Zaf5OQ8ZP](https://github.com/Crunchepillar/Lethal-Company-Enhancer/assets/25714580/07da10be-c646-4c68-93eb-21cfa9c22806)

**Comment by RobynLlama** [comment]
Yea I probably should only let despawn run on the host. Is it actually causing anything weird in game or just an error?

**Comment by sockbats** [comment]
Yeah whenever it happened I got stuck in the death spectating screen, causing us to have to restart the lobby.

**Comment by RobynLlama** [comment]
fixed a few weeks ago but I forgor to close this issue
